import streamlit as st
import os
import base64

# Define the path to the image folder
image_folder = os.path.join(os.getcwd(), "images")

# Define the list of units and map them to local .jpg image file paths in the /images folder
unit_images = {
    "Crawler": "crawler.jpg",
    "Fang": "fang.jpg",
    "Marksman": "marksman.jpg",
    "Arclight": "arclight.jpg",
    "Wasp": "wasp.jpg",
    "Mustang": "mustang.jpg",
    "Sledgehammer": "sledgehammer.jpg",
    "Steelballs": "steelball.jpg",
    "Stormcaller": "stormcaller.jpg",
    "Phoenix": "phoenix.jpg",
    "Rhino": "rhino.jpg",
    "Hacker": "hacker.jpg",
    "Wraith": "wraith.jpg",
    "Scorpion": "scorpion.jpg",
    "Vulcan": "vulcan.jpg",
    "Fortress": "fortress.jpg",
    "Melting Point": "melting_point.jpg",
    "Overlord": "overlord.jpg",
    "Sandworm": "sandworm.jpg",
    "War Factory": "war_factory.jpg",
    "Fire Badger": "fire_badger.jpg",
    "Typhoon": "typhoon.jpg",
    "Sabertooth": "sabertooth.jpg",
    "Tarantula": "tarantula.jpg",
    "Farseer": "farseer.jpg",
    "Phantom Ray": "phantom_ray.jpg",
    "Raiden": "raiden.jpg",
}

# Matrix key
# S = 6 # unit wins, >95% HP left
# A = 5 # unit wins, 60-95% HP left
# B = 4 # unit wins, 10-60% HP left
# C = 3 # unit wins, <10% HP left
# D = 2 # unit lose, Opponent <10% HP left
# E = 1 # unit lose, Opponent 10-50% HP left
# F = 0 # unit lose, Opponent >50% HP left
# Load unit matrix and overrides into Pandas DataFrames
unit_matrix_data = {
    # Add the matrix data for counters here as columns
    "Crawler": [
        2,
        5,
        5,
        0,
        0,
        4,
        1,
        4,
        4,
        0,
        4,
        5,
        0,
        1,
        0,
        1,
        4,
        0,
        1,
        0,
        0,
        0,
        4,
        0,
        0,
        0,
        0,
    ],
    "Fang": [
        1,
        2,
        5,
        0,
        5,
        0,
        0,
        4,
        0,
        5,
        2,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        4,
        4,
    ],
    "Marksman": [
        0,
        0,
        2,
        6,
        1,
        0,
        2,
        3,
        1,
        4,
        2,
        6,
        3,
        0,
        0,
        0,
        0,
        0,
        6,
        0,
        5,
        1,
        1,
        4,
        1,
        2,
        0,
    ],
    "Arclight": [
        6,
        6,
        0,
        2,
        6,
        5,
        0,
        0,
        0,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
    ],
    "Wasp": [
        6,
        0,
        4,
        0,
        2,
        0,
        6,
        6,
        6,
        5,
        6,
        6,
        1,
        6,
        6,
        0,
        4,
        4,
        1,
        6,
        6,
        0,
        6,
        0,
        0,
        5,
        5,
    ],
    "Mustang": [
        1,
        4,
        5,
        0,
        6,
        2,
        0,
        0,
        4,
        5,
        1,
        5,
        2,
        0,
        0,
        1,
        4,
        4,
        1,
        0,
        0,
        0,
        2,
        0,
        0,
        5,
        5,
    ],
    "Sledgehammer": [
        4,
        5,
        3,
        5,
        0,
        5,
        2,
        0,
        4,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
    ],
    "Steelballs": [
        1,
        2,
        0,
        4,
        0,
        4,
        5,
        2,
        6,
        0,
        5,
        0,
        0,
        0,
        4,
        4,
        4,
        0,
        5,
        0,
        4,
        5,
        0,
        5,
        0,
        0,
        0,
    ],
    "Stormcaller": [
        1,
        5,
        4,
        6,
        0,
        1,
        1,
        0,
        2,
        0,
        0,
        6,
        0,
        2,
        5,
        4,
        5,
        0,
        0,
        0,
        0,
        1,
        4,
        4,
        1,
        0,
        0,
    ],
    "Phoenix": [
        6,
        0,
        1,
        4,
        0,
        0,
        6,
        6,
        6,
        2,
        6,
        6,
        3,
        6,
        6,
        0,
        1,
        0,
        0,
        6,
        6,
        0,
        6,
        2,
        1,
        1,
        1,
    ],
    "Rhino": [
        1,
        3,
        3,
        5,
        4,
        0,
        5,
        0,
        6,
        0,
        2,
        6,
        0,
        0,
        4,
        1,
        0,
        0,
        2,
        0,
        5,
        4,
        4,
        3,
        4,
        0,
        0,
    ],
    "Hacker": [
        0,
        0,
        0,
        4,
        0,
        0,
        4,
        6,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        6,
        1,
        0,
        0,
        0,
        0,
        0,
    ],
    "Wraith": [
        6,
        5,
        2,
        4,
        4,
        3,
        6,
        6,
        6,
        2,
        6,
        6,
        2,
        6,
        6,
        0,
        0,
        0,
        0,
        6,
        6,
        0,
        6,
        2,
        0,
        1,
        0,
    ],
    "Scorpion": [
        4,
        6,
        4,
        6,
        0,
        5,
        6,
        6,
        3,
        0,
        6,
        6,
        0,
        2,
        4,
        0,
        0,
        0,
        0,
        0,
        6,
        6,
        4,
        6,
        4,
        0,
        0,
    ],
    "Vulcan": [
        6,
        6,
        5,
        6,
        0,
        6,
        4,
        1,
        0,
        0,
        1,
        6,
        0,
        1,
        2,
        0,
        0,
        0,
        0,
        0,
        6,
        5,
        1,
        4,
        4,
        0,
        0,
    ],
    "Fortress": [
        4,
        5,
        5,
        6,
        5,
        4,
        5,
        1,
        1,
        4,
        4,
        6,
        5,
        4,
        5,
        2,
        0,
        1,
        3,
        0,
        6,
        6,
        4,
        5,
        5,
        1,
        4,
    ],
    "Melting Point": [
        1,
        5,
        5,
        6,
        1,
        1,
        4,
        1,
        0,
        4,
        5,
        6,
        6,
        4,
        6,
        4,
        2,
        4,
        4,
        4,
        5,
        6,
        4,
        6,
        5,
        4,
        5,
    ],
    "Overlord": [
        6,
        5,
        5,
        6,
        1,
        1,
        6,
        6,
        6,
        4,
        6,
        6,
        6,
        6,
        6,
        4,
        1,
        2,
        2,
        6,
        6,
        4,
        6,
        6,
        5,
        5,
        5,
    ],
    "Sandworm": [
        4,
        5,
        6,
        6,
        4,
        4,
        5,
        0,
        6,
        5,
        3,
        6,
        5,
        4,
        5,
        2,
        0,
        3,
        2,
        1,
        5,
        6,
        4,
        5,
        6,
        4,
        6,
    ],
    "War Factory": [
        6,
        6,
        5,
        6,
        0,
        6,
        6,
        6,
        4,
        0,
        6,
        6,
        0,
        5,
        5,
        4,
        1,
        0,
        4,
        2,
        6,
        6,
        5,
        6,
        5,
        0,
        0,
    ],
    "Fire Badger": [
        6,
        5,
        0,
        4,
        0,
        5,
        4,
        0,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
    ],
    "Typhoon": [
        6,
        6,
        4,
        4,
        6,
        6,
        4,
        0,
        4,
        5,
        0,
        4,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        2,
        0,
        3,
        1,
        5,
        1,
    ],
    "Sabertooth": [
        0,
        3,
        4,
        6,
        0,
        3,
        4,
        5,
        1,
        0,
        5,
        6,
        0,
        1,
        4,
        1,
        1,
        0,
        1,
        0,
        6,
        4,
        2,
        5,
        4,
        0,
        0,
    ],
    "Tarantula": [
        6,
        6,
        1,
        4,
        6,
        5,
        4,
        0,
        1,
        3,
        0,
        6,
        3,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        2,
        0,
        2,
        1,
        3,
        0,
    ],
    "Farseer": [
        6,
        6,
        4,
        6,
        6,
        6,
        5,
        4,
        4,
        4,
        1,
        6,
        4,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        5,
        4,
        1,
        4,
        2,
        5,
        2,
    ],
    "Phantom Ray": [
        6,
        0,
        2,
        4,
        0,
        0,
        6,
        6,
        6,
        4,
        6,
        6,
        4,
        6,
        6,
        4,
        1,
        0,
        1,
        6,
        6,
        0,
        6,
        2,
        0,
        2,
        0,
    ],
    "Raiden": [
        6,
        1,
        5,
        6,
        0,
        0,
        6,
        6,
        6,
        4,
        6,
        6,
        5,
        6,
        6,
        1,
        0,
        0,
        0,
        6,
        6,
        4,
        6,
        4,
        3,
        5,
        2,
    ],
}


UNITS = list(unit_matrix_data.keys())

st.set_page_config(layout="wide", page_title="Mechabellum Unit Counters")

# Sidebar configuration
cols_per_row = st.sidebar.slider(
    "Select the number of columns per row:", min_value=2, max_value=24, value=13, step=1
)
cols_per_row_output = st.sidebar.slider(
    "Select the number of columns per row for output:",
    min_value=5,
    max_value=24,
    value=16,
    step=1,
)
show_sliders = st.sidebar.checkbox("Show Weight Sliders")

# Initialize session state
if "selected_units" not in st.session_state:
    st.session_state.selected_units = []
if "weights" not in st.session_state:
    st.session_state.weights = {unit: 1 for unit in unit_images.keys()}


# Helper function to convert image to base64
def get_image_as_base64(img_path):
    with open(img_path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode()


# Display unit selection grid
def display_unit_selection_grid(unit_list, cols_per_row, show_sliders):
    num_units = len(unit_list)
    for i in range(0, num_units, cols_per_row):
        cols = st.columns(cols_per_row)
        for j, unit in enumerate(unit_list[i : i + cols_per_row]):
            with cols[j]:
                if st.checkbox(
                    f" ",
                    key=f"checkbox:{unit}",
                    value=(unit in st.session_state.selected_units),
                ):
                    if unit not in st.session_state.selected_units:
                        st.session_state.selected_units.append(unit)
                else:
                    if unit in st.session_state.selected_units:
                        st.session_state.selected_units.remove(unit)

                border_style = (
                    "border: 3px solid black;"
                    if unit in st.session_state.selected_units
                    else "border: 3px solid transparent;"
                )
                img_path = os.path.join(image_folder, unit_images[unit])
                img_base64 = get_image_as_base64(img_path)

                st.markdown(
                    f"""
                    <div style="text-align: center;">
                        <img src="data:image/jpeg;base64,{img_base64}" style="width:100%; {border_style} border-radius: 10px;">
                        <p>{unit}</p>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

                if show_sliders and unit in st.session_state.selected_units:
                    st.session_state.weights[unit] = st.slider(
                        f" ",
                        key=f"slider:{unit}",
                        min_value=1,
                        max_value=5,
                        value=st.session_state.weights[unit],
                    )


# Function to calculate the counter score
def get_counter_score(selected_units, unit_matrix_data, weights):
    scores = {unit: 0 for unit in UNITS}
    div = {unit: 0 for unit in UNITS}

    for selected in selected_units:
        for unit, counters in unit_matrix_data.items():
            index = UNITS.index(selected)
            scores[unit] += counters[index] * weights[selected]
            div[unit] += weights[selected]

    if selected_units:
        scores = {k: scores[k] / div[k] if scores[k] > 0 else 0 for k in scores.keys()}
    return sorted(scores.items(), key=lambda x: x[1], reverse=True)


# Function to classify units into tiers based on score
def classify_by_tier(best_counters):
    tier_bins = {
        "S Tier (6 points)": [],
        "A Tier (5 points)": [],
        "B Tier (4 points)": [],
        "C Tier (3 points)": [],
        "D/E/F Tier (0-2 points)": [],
    }

    for unit, score in best_counters:
        if score == 6:
            tier_bins["S Tier (6 points)"].append(unit)
        elif score == 5:
            tier_bins["A Tier (5 points)"].append(unit)
        elif score == 4:
            tier_bins["B Tier (4 points)"].append(unit)
        elif score == 3:
            tier_bins["C Tier (3 points)"].append(unit)
        else:
            tier_bins["D/E/F Tier (0-2 points)"].append(unit)

    return tier_bins


# Display the best counter units in matrix format
def display_best_counters(tiered_counters, cols_per_row_output):
    st.write("Best Counter Units by Tier:")
    for tier, units in tiered_counters.items():
        st.markdown(f"**{tier}**")
        if units:
            cols = st.columns(cols_per_row_output)
            for idx, unit in enumerate(units):
                base_unit = unit.split(":")[0].strip() if ":" in unit else unit
                img_path = os.path.join(image_folder, unit_images[base_unit])
                img_base64 = get_image_as_base64(img_path)

                with cols[idx % cols_per_row_output]:
                    st.markdown(
                        f"""
                        <div style="text-align: center;">
                            <img src="data:image/jpeg;base64,{img_base64}" style="width:100%; border-radius: 10px;">
                            <p><b>{unit.split(":")[1].strip() if ":" in unit else ""}</b></p>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )


# Main execution
unit_list = list(unit_images.keys())
display_unit_selection_grid(unit_list, cols_per_row, show_sliders)

selected_units = st.session_state.selected_units
raw_weights = st.session_state.weights
total_weight = sum(raw_weights.values())
weights = {
    unit: (raw_weights[unit] / total_weight) if unit in raw_weights else 0
    for unit in UNITS
}

best_counters = get_counter_score(selected_units, unit_matrix_data, weights)
tiered_counters = classify_by_tier(best_counters)
display_best_counters(tiered_counters, cols_per_row_output)
